### ISSUE TITLE
setup Jest and React testing library for unit testing

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/redesigner.io#10]
- [ ] Install jest, React testing library
- [ ] write unit tests for Header.tsx component

Help URL: https://nextjs.org/docs/pages/building-your-application/optimizing/testing

**Comment by lausuarez02** [comment]
Hey Kirandash,
I would like to help you taking this issue if you like.
If you let me i would assign it to me.
Cheers mate

**Comment by kirandash** [comment]
> Hey Kirandash, I would like to help you taking this issue if you like. If you let me i would assign it to me. Cheers mate

Thanks @lausuarez02 🙏 for showing your interest! I have now assigned the task to you.

If you need any help, you can comment here or reach me on discord at:

[discord.gg/62VR3MMCVm](https://discord.gg/62VR3MMCVm)

And if you like this project, please do show your support by leaving a star ⭐️ for more visibility
