### ISSUE TITLE
Update Favicon

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/redesigner.io#11]
Currently the favicon says "RP", Please update it to "RD"

You can generate the favicon at: https://favicon.io/

You can use the following settings to generate the favicon:

![image](https://github.com/bgwebagency/redesigner.io/assets/13310363/155ca67e-5e2d-4d52-b190-832783979ad1)

**Comment by kirandash** [comment]
Thanks @GrumpyArdias  🙏 for showing your interest! I have now assigned the task to you.

If you need any help, you can comment here or reach me on discord at:

[discord.gg/62VR3MMCVm](https://discord.gg/62VR3MMCVm)

And if you like this project, please do show your support by leaving a star ⭐️ for more visibility

**Comment by GrumpyArdias** [comment]
I've done it! I have issue making the push request I wrote yo you in discord!

**Comment by kirandash** [comment]
Deployed to prod!

Working fine!

![image](https://github.com/bgwebagency/redesigner.io/assets/13310363/0f11e721-6cb1-4667-8073-d39b809666ae)

**Comment by kirandash** [comment]
Thanks @GrumpyArdias for your contribution! 🙏🏻

**Comment by GrumpyArdias** [comment]
Nice, thanks! I will keep working on this!

**Comment by kirandash** [comment]
> Nice, thanks! I will keep working on other issues!

Great! Feel free to reach me if you need any help. 
Also FYI, I do have other open source projects if you don't find any issues of your interest on this project. You can check them out.

Happy Coding!
