### ISSUE TITLE
Add to the readme how to start the app

### ISSUE THREAD

**Issue by lausuarez02** [bgwebagency/redesigner.io#17]
Hey kirandash,
I'm adding this new, please assign it to  @/GrumpyArdias
 
I've noticed that the readme does not have info about how to start the app.

**Comment by kirandash** [comment]
Thanks for your contribution @GrumpyArdias

**Comment by kirandash** [comment]
![image](https://github.com/bgwebagency/redesigner.io/assets/13310363/9f2c0199-cd51-4100-bcaa-6fc0a3febb22)

@GrumpyArdias I am reopening this issue.

I only reviewed the content. But forgot to check the formatting. There are some formatting issues. Please have a look

If you need any help, then let me know

**Comment by GrumpyArdias** [comment]
I check it out in https://stackedit.io/app# and make some changes, hope now works fine.

**Comment by kirandash** [comment]
Thanks! Please create PR. So I can review the changes

**Comment by kirandash** [comment]
Fixed!

**Comment by lausuarez02** [comment]
Hey, 
I want to reopen the ticket. 

6. I would choose to use **switch** over **checkout** since checkout it was originally created to create a new branch a move into it whereas **switch** was created to literally switch between branches.

8. Here i would like to introduce a standar of commit to be able to understand what you have done following conventional commits as follows <type>[optional scope]: <description>. https://www.conventionalcommits.org/en/v1.0.0/

**Comment by kirandash** [comment]
> Hey, 
> 
> I want to reopen the ticket. 
> 
> 
> 
> 6. I would choose to use **switch** over **checkout** since checkout it was originally created to create a new branch a move into it whereas **switch** was created to literally switch between branches.
> 
> 
> 
> 8. Here i would like to introduce a standar of commit to be able to understand what you have done following conventional commits as follows <type>[optional scope]: <description>. https://www.conventionalcommits.org/en/v1.0.0/
> 
> 

Thanks for pointing that out. Pls go ahead
