### ISSUE TITLE
create thumbnails for building themes

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/redesigner.io#2]
URL: https://www.redesigner.io/building

![image](https://github.com/bgwebagency/redesigner.io/assets/13310363/f5bdc85c-6532-4caf-9fd1-8db562033c4a)

Currently building themes are represented by text.

We need to create images to represent each theme.

- [ ] pick image of a house from [unsplash](https://unsplash.com/s/photos/house?license=free). Make sure the image is free for use by choosing free license filter
- [ ] use our app to redesign the same house in all different themes.
- [ ] check if result is clean. If not, try another image from [unsplash](https://unsplash.com/)
- [ ] name all images in the format `${building}-${theme}.jpg` ex: house-rustic.jpg, house-minimalist.jpg and so on
- [ ] And then use some image editing tool to resize al images to 100 x 100 size and then upload them to /public folder

**Comment by GrumpyArdias** [comment]
I would like to do this!
