### ISSUE TITLE
.env configuration

### ISSUE THREAD

**Issue by baranero** [bgwebagency/redesigner.io#34]
Maybe it's worth to describe in README for beginners how to configure .env to run applications locally. And of course not to push the .env to the repository.

**Comment by kirandash** [comment]
yes that would be a great addition to the Documentation 

Thanks for creating the issue

**Comment by GrumpyArdias** [comment]
I will do it!

**Comment by GrumpyArdias** [comment]
I check out, the code, in local I see works fine, but here not I will solve it, don close this issue

**Comment by kirandash** [comment]
> I check out, the code, in local I see works fine, but here not I will solve it, don close this issue

sorry, I don't understand. what's not working?

**Comment by GrumpyArdias** [comment]
this is form GitHub readme: 
![image](https://github.com/bgwebagency/redesigner.io/assets/86208410/4d0700d6-e7e7-4797-8153-ce0479408fc7)

and this is from my  computer 
![image](https://github.com/bgwebagency/redesigner.io/assets/86208410/175e276a-ae4b-4bc9-b1d2-15b1732b1ac7)

**Comment by baranero** [comment]
Maybe use break line <br> tag?

**Comment by GrumpyArdias** [comment]
yes, I'm adding br, but i dont know if is gonna work fine, so I'm looking for information about how MarkDown works in GitHub

**Comment by baranero** [comment]
Also you can try add images not through HTML tag but in this way `![alt](image_path)`

**Comment by GrumpyArdias** [comment]
I try it,  at first, but didn't work so I change to img tag, I create also the gif and I use the ![]() of markdown

**Comment by GrumpyArdias** [comment]
Ok I see still one of the pictures are wrong! I will check it out!

**Comment by GrumpyArdias** [comment]
This is fix, we can close the issue
