### ISSUE TITLE
Add dark and light theme switch to header

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/redesigner.io#36]
You can get the sun and moon icon from [react-icons](https://react-icons.github.io/react-icons/search?q=sun) or [hero-icons](https://heroicons.com/) and change the tailwind theme from dark to light

Position the icon after the github icon

**Comment by u01qureshi** [comment]
Hi, I would like to work on this issue. If it is okay, can you assign this issue to me?

**Comment by kirandash** [comment]
Thanks @u01qureshi  🙏 for showing your interest! I have now assigned the task to you.

If you need any help, you can comment here or reach me on discord at:

[discord.gg/62VR3MMCVm](https://discord.gg/62VR3MMCVm)

And if you like this project, please do show your support by leaving a star ⭐️ so more people can find it

Happy Coding!
