### ISSUE TITLE
The Github icon on header is almost invisible on the light theme

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/redesigner.io#4]
The foreground changes color accordingly to the theme (light or dark), but the GitHub icon at the top right corner is an SVG so it is always white, therefore it is almost invisible on the light theme.

Please replace this with the GitHub icon from the "react-icons/ai" library instead (like it is done for the icons on footer).

**Comment by baranero** [comment]
I took care of it.

**Comment by kirandash** [comment]
Deployed to Prod

![image](https://github.com/bgwebagency/redesigner.io/assets/13310363/fb1fd44f-c2d4-4b60-9bb4-19b899404b57)

**Comment by kirandash** [comment]
@baranero Thanks for your contribution. 🙏🏻

If you would like to contribute more, please have a look at open issues on this and other open source projects of mine.

Also, if you are interested in learning how this project is built and want to build your own AI app, I have a full tutorial at: https://youtu.be/4YXUGuo9OM4

Happy Coding!
