### ISSUE TITLE
Unit Tests for footer component

### ISSUE THREAD

**Issue by lausuarez02** [bgwebagency/redesigner.io#40]
Add unit tests for footer component

**Comment by baranero** [comment]
I'll take it

**Comment by kirandash** [comment]
@lausuarez02 Thanks for creating the task. But can you please make it more precise. Maybe create individual issues for each component. Ex: Separate unit test issue for footer, themeselector etc components.

I will update description for this task to add unit test for footer component.

@baranero please work only on footer unit tests for this task.
