### ISSUE TITLE
Missing image for building theme selector

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/redesigner.io#57]
Hi, I found a error:

![image](https://github.com/bgwebagency/redesigner.io/assets/86208410/81e05137-a620-4dd9-a4ab-837b3df43b6c)

_Originally posted by @GrumpyArdias in https://github.com/bgwebagency/redesigner.io/issues/7#issuecomment-1600743837_

**Comment by GrumpyArdias** [comment]
For me this one!

**Comment by GrumpyArdias** [comment]
This is fix, we can close the issue
