### ISSUE TITLE
align footer icons to center

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/redesigner.io#62]
![image](https://github.com/bgwebagency/redesigner.io/assets/13310363/08a11015-3b95-4c4b-875a-8465285e8721)

Currently the footer icons are aligned to the right. Please align them to the center

**Comment by hashnj** [comment]
assign me 😃

**Comment by hashnj** [comment]
hey, i am new to open source. i have fixed the issue, and i am getting another issue when i am trying to create the pull req. the bot says i am trying to deploy a commit, which i'm not i'm just trying to get your approval by making a pull req. please check it, is it meant to do so
as i said i am new to github alltoghter so i don't know

**Comment by kirandash** [comment]
> hey, i am new to open source. i have fixed the issue, and i am getting another issue when i am trying to create the pull req. the bot says i am trying to deploy a commit, which i'm not i'm just trying to get your approval by making a pull req. please check it, is it meant to do so as i said i am new to github alltoghter so i don't know

don't worry about that. It's not deploying. The message means: the changes will be deployed when I merge it.

**Comment by hashnj** [comment]
ok, thankyou for letting me know
