### ISSUE TITLE
add loading state on page navigation

### ISSUE THREAD

**Issue by kirandash** [bgwebagency/redesigner.io#9]
from home page, on clicking "Redesign room" the page navigates to [https://www.redesigner.io/room](https://www.redesigner.io/room)

currently there is no loading indicator

Let's add a loader:

[mhnpd.github.io/react-loader-spinner/docs/components/rotating-lines](https://mhnpd.github.io/react-loader-spinner/docs/components/rotating-lines)

same need to happen for other page navigations too

**Comment by belenwebdev** [comment]
Hello @kirandash , I would like to work on this issue. If that's ok, could I assign it to me?

**Comment by kirandash** [comment]
Thanks @belenwebdev 🙏 for showing your interest! I have now assigned the task to you.

If you need any help, you can comment here or reach me on discord at:

[discord.gg/62VR3MMCVm](https://discord.gg/62VR3MMCVm)

And if you like this project, please do show your support by leaving a star ⭐️ for more visibility

Happy Coding!
